module.exports = (data) => data.map(record => ({
    imei: parseInt(packet.imei),
    voltage: record['external.powersource.voltage'],
    ibutton_code: record['ibutton.code'],
    timestamp: new Date(record.timestamp * 1000),
    channel_id: record['channel.id'],
    din: record.din,
    longitude: record['position.longitude'],
    latitude: record['position.latitude'],
    altitude: record['position.altitude'],
    direction: record['position.direction'],
    satellites: record['position.satellites'],
    speed: record['position.speed'],
    hdop: record['position.hdop'],
    event_id: record['event.id'],
    acceleration_events: record['segment.acceleration.events'],
    cornering_events: record['segment.cornering.events'],
    extreme_braking_events: record['segment.extreme.braking.events'],
    harsh_braking_events: record['segment.harsh.braking.events'],
}));
